# Generated by Django 5.2.4 on 2025-07-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(blank=True, default='default.png', max_length=100),
        ),
    ]
