# Generated by Django 5.2.4 on 2025-07-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0002_employees_photofilename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='PhotoFileName',
        ),
    ]
