# Generated by Django 5.2.4 on 2025-07-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0005_employees_photofilename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='PhotoFileName',
        ),
        migrations.AlterField(
            model_name='departments',
            name='DepartmentId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='EmployeeId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
