# Generated by Django 5.2.4 on 2025-07-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0006_remove_employees_photofilename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(blank=True, default='default.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='departments',
            name='DepartmentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='EmployeeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
