# Generated by Django 5.2.4 on 2025-07-12 12:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import empApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0007_employees_photofilename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='DepartmentName',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Department name must contain only letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='DateOfJoining',
            field=models.DateField(validators=[empApp.models.validate_no_future_date]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='empApp.departments'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='EmployeeName',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Employee name must contain only letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(blank=True, default='default.png', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='departments',
            index=models.Index(fields=['DepartmentName'], name='empApp_depa_Departm_9e9236_idx'),
        ),
        migrations.AddIndex(
            model_name='employees',
            index=models.Index(fields=['EmployeeName'], name='empApp_empl_Employe_810554_idx'),
        ),
        migrations.AddIndex(
            model_name='employees',
            index=models.Index(fields=['Department'], name='empApp_empl_Departm_960ad3_idx'),
        ),
    ]
