# Generated by Django 5.2.4 on 2025-07-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0008_departments_createdat_departments_updatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
